import AsyncStorage from "@react-native-async-storage/async-storage";
import React, { createContext, useCallback, useContext, useEffect, useState } from "react";
import { useAuth } from "./AuthContext";

export interface RoadmapModule {
  id: string;
  week: number;
  topic: string;
  description: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  tasks: string[];
  resources: { title: string; url: string; type: "video" | "article" | "course" }[];
  completed: boolean;
}

export interface Roadmap {
  id: string;
  userId: string;
  title: string;
  role: string;
  level: string;
  modules: RoadmapModule[];
  createdAt: string;
}

interface RoadmapContextType {
  roadmap: Roadmap | null;
  isGenerating: boolean;
  generateRoadmap: (skillGaps: string[], targetRole: string, experienceLevel?: string) => Promise<void>;
  toggleModule: (moduleId: string) => Promise<void>;
  clearRoadmap: () => Promise<void>;
}

const ROLE_ROADMAPS: Record<string, RoadmapModule[]> = {
  frontend: [
    { id: "f1", week: 1, topic: "Modern HTML & CSS Mastery", description: "Semantic HTML5, CSS Grid, Flexbox, and responsive design fundamentals.", level: "Beginner", tasks: ["Build a responsive portfolio page", "Implement CSS Grid layouts", "Master Flexbox alignment"], resources: [{ title: "CSS Grid by Kevin Powell", url: "https://www.youtube.com/watch?v=rg7Fvvl3taU", type: "video" }, { title: "MDN Web Docs — CSS", url: "https://developer.mozilla.org/en-US/docs/Web/CSS", type: "article" }], completed: false },
    { id: "f2", week: 2, topic: "JavaScript Deep Dive", description: "Closures, prototypes, async/await, and the event loop.", level: "Intermediate", tasks: ["Solve 10 JS challenges on LeetCode", "Build a Promise-based API client", "Understand the event loop"], resources: [{ title: "JavaScript.info", url: "https://javascript.info", type: "article" }, { title: "Async JS — freeCodeCamp", url: "https://www.freecodecamp.org/news/asynchronous-javascript/", type: "article" }], completed: false },
    { id: "f3", week: 3, topic: "React & State Management", description: "Hooks, context, performance patterns, and React Query.", level: "Intermediate", tasks: ["Build a CRUD app with hooks", "Implement optimistic updates", "Add React Query for server state"], resources: [{ title: "React Docs", url: "https://react.dev", type: "article" }, { title: "TanStack Query Docs", url: "https://tanstack.com/query", type: "article" }], completed: false },
    { id: "f4", week: 4, topic: "TypeScript for Frontend", description: "Types, generics, utility types, and strict mode patterns.", level: "Intermediate", tasks: ["Convert a JS project to TypeScript", "Write 5 custom generic types", "Enable strict mode without errors"], resources: [{ title: "TypeScript Handbook", url: "https://www.typescriptlang.org/docs/handbook/", type: "article" }, { title: "TypeScript Deep Dive", url: "https://basarat.gitbook.io/typescript/", type: "article" }], completed: false },
    { id: "f5", week: 5, topic: "Performance Optimization", description: "Lighthouse, bundle optimization, code splitting, and lazy loading.", level: "Advanced", tasks: ["Achieve 90+ Lighthouse score", "Implement code splitting with dynamic imports", "Reduce bundle size by 30%"], resources: [{ title: "Web.dev Performance", url: "https://web.dev/performance", type: "article" }, { title: "Webpack Bundle Analyzer", url: "https://github.com/webpack-contrib/webpack-bundle-analyzer", type: "article" }], completed: false },
    { id: "f6", week: 6, topic: "Testing Frontend Apps", description: "Unit, integration, and E2E testing with Jest, RTL, and Playwright.", level: "Intermediate", tasks: ["Add unit tests with React Testing Library", "Write 3 E2E tests with Playwright", "Achieve 80% code coverage"], resources: [{ title: "Testing Library Docs", url: "https://testing-library.com", type: "article" }, { title: "Playwright Docs", url: "https://playwright.dev", type: "article" }], completed: false },
    { id: "f7", week: 7, topic: "CSS Architecture & Design Systems", description: "CSS Modules, Tailwind, component libraries, and tokens.", level: "Intermediate", tasks: ["Build a mini design system with 10 components", "Implement CSS custom properties for theming", "Create dark mode support"], resources: [{ title: "Tailwind CSS Docs", url: "https://tailwindcss.com/docs", type: "article" }, { title: "Storybook Tutorial", url: "https://storybook.js.org/tutorials/", type: "article" }], completed: false },
    { id: "f8", week: 8, topic: "Forms & Validation", description: "React Hook Form, Zod, accessible forms, and complex validations.", level: "Intermediate", tasks: ["Build a multi-step form", "Add Zod schema validation", "Implement accessible error states"], resources: [{ title: "React Hook Form Docs", url: "https://react-hook-form.com", type: "article" }, { title: "Zod Documentation", url: "https://zod.dev", type: "article" }], completed: false },
    { id: "f9", week: 9, topic: "API Integration & Data Fetching", description: "REST, GraphQL, SWR vs React Query, and error handling.", level: "Advanced", tasks: ["Build a GraphQL client with Apollo", "Implement offline support with SWR", "Handle optimistic updates"], resources: [{ title: "Apollo Client Docs", url: "https://www.apollographql.com/docs/react/", type: "article" }, { title: "SWR Docs", url: "https://swr.vercel.app", type: "article" }], completed: false },
    { id: "f10", week: 10, topic: "Accessibility (A11y)", description: "WCAG guidelines, ARIA roles, keyboard navigation, and screen readers.", level: "Intermediate", tasks: ["Audit a page with axe DevTools", "Fix 10 accessibility issues", "Add keyboard navigation to a dropdown"], resources: [{ title: "WCAG Guidelines", url: "https://www.w3.org/WAI/WCAG21/quickref/", type: "article" }, { title: "A11y Project", url: "https://www.a11yproject.com", type: "article" }], completed: false },
    { id: "f11", week: 11, topic: "Build Tools & CI/CD", description: "Vite, esbuild, GitHub Actions, and automated deployment pipelines.", level: "Advanced", tasks: ["Set up Vite for a project", "Create a GitHub Actions CI pipeline", "Deploy to Vercel/Netlify automatically"], resources: [{ title: "Vite Guide", url: "https://vitejs.dev/guide/", type: "article" }, { title: "GitHub Actions Docs", url: "https://docs.github.com/en/actions", type: "article" }], completed: false },
    { id: "f12", week: 12, topic: "Portfolio & Career Prep", description: "Build a portfolio, optimize LinkedIn, and prepare for frontend interviews.", level: "Beginner", tasks: ["Build and deploy your portfolio", "Solve 20 frontend interview questions", "Record a 5-min code walkthrough video"], resources: [{ title: "Frontend Interview Handbook", url: "https://www.frontendinterviewhandbook.com", type: "article" }, { title: "Great Frontend Challenges", url: "https://www.greatfrontend.com", type: "course" }], completed: false },
  ],
  backend: [
    { id: "bk1", week: 1, topic: "API Design & HTTP Mastery", description: "REST principles, HTTP verbs, status codes, and OpenAPI spec.", level: "Beginner", tasks: ["Design a RESTful API for a blog", "Write an OpenAPI spec", "Implement CRUD with validation"], resources: [{ title: "REST API Design Best Practices", url: "https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/", type: "article" }, { title: "Swagger / OpenAPI Guide", url: "https://swagger.io/docs/specification/about/", type: "article" }], completed: false },
    { id: "bk2", week: 2, topic: "Databases & Query Optimization", description: "PostgreSQL indexing, query plans, and ORM best practices.", level: "Intermediate", tasks: ["Optimize slow queries with EXPLAIN", "Add indexes to a schema", "Implement full-text search"], resources: [{ title: "PostgreSQL Tutorial", url: "https://www.postgresqltutorial.com", type: "article" }, { title: "Drizzle ORM Docs", url: "https://orm.drizzle.team", type: "article" }], completed: false },
    { id: "bk3", week: 3, topic: "Authentication & Security", description: "JWT, OAuth2, rate limiting, input validation, and OWASP top 10.", level: "Intermediate", tasks: ["Implement JWT auth", "Add rate limiting", "Sanitize all inputs"], resources: [{ title: "OWASP Top 10", url: "https://owasp.org/www-project-top-ten/", type: "article" }, { title: "Auth0 Security Blog", url: "https://auth0.com/blog/", type: "article" }], completed: false },
    { id: "bk4", week: 4, topic: "Caching & Redis", description: "Redis data structures, TTL strategies, and cache invalidation.", level: "Advanced", tasks: ["Add Redis caching layer", "Implement cache-aside pattern", "Build a session store with Redis"], resources: [{ title: "Redis University — RU101", url: "https://university.redis.com/courses/ru101/", type: "course" }, { title: "Redis Best Practices", url: "https://redis.io/docs/manual/patterns/", type: "article" }], completed: false },
    { id: "bk5", week: 5, topic: "Message Queues & Event-Driven", description: "Kafka, RabbitMQ, pub/sub patterns, and async processing.", level: "Advanced", tasks: ["Set up a Kafka producer/consumer", "Implement dead letter queues", "Build an event-driven order system"], resources: [{ title: "Kafka Quickstart", url: "https://kafka.apache.org/quickstart", type: "article" }, { title: "RabbitMQ Tutorials", url: "https://www.rabbitmq.com/tutorials", type: "article" }], completed: false },
    { id: "bk6", week: 6, topic: "Microservices Architecture", description: "Service decomposition, API gateways, and inter-service communication.", level: "Advanced", tasks: ["Split a monolith into 3 services", "Set up an API gateway", "Implement circuit breaker pattern"], resources: [{ title: "Microservices.io Patterns", url: "https://microservices.io/patterns/index.html", type: "article" }, { title: "Martin Fowler on Microservices", url: "https://martinfowler.com/articles/microservices.html", type: "article" }], completed: false },
    { id: "bk7", week: 7, topic: "Testing Backend Systems", description: "Unit tests, integration tests, contract testing, and load testing.", level: "Intermediate", tasks: ["Write 20 unit tests for an API", "Add integration tests with a test database", "Run a load test with k6"], resources: [{ title: "Jest Docs", url: "https://jestjs.io/docs/getting-started", type: "article" }, { title: "k6 Load Testing", url: "https://k6.io/docs/", type: "article" }], completed: false },
    { id: "bk8", week: 8, topic: "Distributed Systems Fundamentals", description: "CAP theorem, consistency models, distributed transactions, and SAGA.", level: "Advanced", tasks: ["Study CAP theorem with examples", "Implement optimistic locking", "Design a distributed transaction flow"], resources: [{ title: "Designing Data-Intensive Applications", url: "https://dataintensive.net", type: "article" }, { title: "System Design Primer", url: "https://github.com/donnemartin/system-design-primer", type: "article" }], completed: false },
    { id: "bk9", week: 9, topic: "Cloud & Deployment", description: "AWS/GCP services, serverless, containerization with Docker.", level: "Intermediate", tasks: ["Deploy an API to AWS Lambda", "Containerize the app with Docker", "Set up auto-scaling"], resources: [{ title: "AWS Free Tier Tutorials", url: "https://aws.amazon.com/getting-started/", type: "course" }, { title: "Docker Official Getting Started", url: "https://docs.docker.com/get-started/", type: "article" }], completed: false },
    { id: "bk10", week: 10, topic: "Observability & Monitoring", description: "Structured logging, metrics, distributed tracing, and alerting.", level: "Advanced", tasks: ["Add structured JSON logging", "Set up Prometheus metrics", "Implement distributed tracing with Jaeger"], resources: [{ title: "OpenTelemetry Docs", url: "https://opentelemetry.io/docs/", type: "article" }, { title: "Prometheus Getting Started", url: "https://prometheus.io/docs/prometheus/latest/getting_started/", type: "article" }], completed: false },
    { id: "bk11", week: 11, topic: "Database Schema Design", description: "Normalization, indexing strategies, migrations, and performance tuning.", level: "Intermediate", tasks: ["Design a normalized schema for an e-commerce app", "Add composite indexes for common queries", "Write reversible migrations"], resources: [{ title: "Database Design for Beginners", url: "https://www.freecodecamp.org/news/database-design-course-for-beginners/", type: "video" }, { title: "Use The Index, Luke", url: "https://use-the-index-luke.com", type: "article" }], completed: false },
    { id: "bk12", week: 12, topic: "Backend Interview Prep", description: "System design interviews, coding patterns, and behavioral questions.", level: "Intermediate", tasks: ["Practice 3 system design problems", "Solve 20 backend-focused LeetCode problems", "Write answers to 10 behavioral questions"], resources: [{ title: "Grokking System Design Interview", url: "https://www.designgurus.io/course/grokking-the-system-design-interview", type: "course" }, { title: "LeetCode Top 150", url: "https://leetcode.com/studyplan/top-interview-150/", type: "course" }], completed: false },
  ],
  "data science": [
    { id: "ds1", week: 1, topic: "Python for Data Science", description: "NumPy, Pandas, data wrangling, and visualization with Matplotlib/Seaborn.", level: "Beginner", tasks: ["Clean a messy Kaggle dataset", "Create 5 meaningful visualizations", "Master groupby and pivot tables"], resources: [{ title: "Kaggle Python Course", url: "https://www.kaggle.com/learn/python", type: "course" }, { title: "Pandas Documentation", url: "https://pandas.pydata.org/docs/", type: "article" }], completed: false },
    { id: "ds2", week: 2, topic: "Machine Learning Fundamentals", description: "Supervised learning, model evaluation, cross-validation, and scikit-learn.", level: "Intermediate", tasks: ["Train and evaluate 3 classification models", "Implement cross-validation", "Create a confusion matrix analysis"], resources: [{ title: "Kaggle ML Course", url: "https://www.kaggle.com/learn/machine-learning", type: "course" }, { title: "Scikit-learn User Guide", url: "https://scikit-learn.org/stable/user_guide.html", type: "article" }], completed: false },
    { id: "ds3", week: 3, topic: "Feature Engineering & EDA", description: "Feature selection, encoding, outlier detection, and exploratory analysis.", level: "Intermediate", tasks: ["Engineer features for a regression problem", "Handle missing data strategically", "Detect and treat outliers"], resources: [{ title: "Feature Engineering for ML — Udemy", url: "https://www.udemy.com/course/feature-engineering-for-machine-learning/", type: "course" }, { title: "Kaggle Feature Engineering", url: "https://www.kaggle.com/learn/feature-engineering", type: "course" }], completed: false },
    { id: "ds4", week: 4, topic: "Statistics & Probability", description: "Hypothesis testing, p-values, A/B testing, and Bayesian fundamentals.", level: "Intermediate", tasks: ["Run an A/B test analysis", "Implement a t-test and chi-square test", "Study Bayes theorem with examples"], resources: [{ title: "Statistics for Data Science — Khan Academy", url: "https://www.khanacademy.org/math/statistics-probability", type: "course" }, { title: "Think Stats (free ebook)", url: "https://greenteapress.com/thinkstats2/html/index.html", type: "article" }], completed: false },
    { id: "ds5", week: 5, topic: "SQL for Data Science", description: "Window functions, CTEs, query optimization, and analytical SQL.", level: "Intermediate", tasks: ["Write 10 window function queries", "Build a cohort analysis query", "Optimize a slow analytical query"], resources: [{ title: "Mode SQL Tutorial", url: "https://mode.com/sql-tutorial/", type: "course" }, { title: "SQLZoo", url: "https://sqlzoo.net", type: "course" }], completed: false },
    { id: "ds6", week: 6, topic: "Deep Learning Foundations", description: "Neural networks, backpropagation, CNNs, and PyTorch basics.", level: "Advanced", tasks: ["Build a neural network from scratch in NumPy", "Train an image classifier with PyTorch", "Implement a custom loss function"], resources: [{ title: "Fast.ai Practical Deep Learning", url: "https://course.fast.ai", type: "course" }, { title: "PyTorch Tutorials", url: "https://pytorch.org/tutorials/", type: "article" }], completed: false },
    { id: "ds7", week: 7, topic: "NLP & Text Analytics", description: "Tokenization, embeddings, transformers, and text classification.", level: "Advanced", tasks: ["Fine-tune a BERT model for sentiment analysis", "Build a text classification pipeline", "Create word embeddings with Word2Vec"], resources: [{ title: "HuggingFace Course", url: "https://huggingface.co/learn/nlp-course/chapter1/1", type: "course" }, { title: "NLTK Book", url: "https://www.nltk.org/book/", type: "article" }], completed: false },
    { id: "ds8", week: 8, topic: "Big Data & Spark", description: "Distributed processing, Spark DataFrames, and Airflow pipelines.", level: "Advanced", tasks: ["Process a 10GB dataset with Spark", "Write a PySpark ETL pipeline", "Build an Airflow DAG for daily data refresh"], resources: [{ title: "Spark: The Definitive Guide", url: "https://www.oreilly.com/library/view/spark-the-definitive/9781491912201/", type: "article" }, { title: "Apache Airflow Docs", url: "https://airflow.apache.org/docs/", type: "article" }], completed: false },
    { id: "ds9", week: 9, topic: "Model Deployment & MLOps", description: "Model serving, FastAPI, Docker, MLflow, and monitoring drift.", level: "Advanced", tasks: ["Deploy a model as a REST API", "Track experiments with MLflow", "Set up data drift monitoring"], resources: [{ title: "MLflow Docs", url: "https://mlflow.org/docs/latest/index.html", type: "article" }, { title: "FastAPI ML Deployment Tutorial", url: "https://fastapi.tiangolo.com/tutorial/", type: "article" }], completed: false },
    { id: "ds10", week: 10, topic: "Data Visualization & Storytelling", description: "Tableau, Plotly, dashboard design, and communicating insights.", level: "Intermediate", tasks: ["Build an interactive dashboard in Plotly", "Create a data story presentation", "Master Tableau Public"], resources: [{ title: "Plotly Python Docs", url: "https://plotly.com/python/", type: "article" }, { title: "Tableau Public Gallery", url: "https://public.tableau.com/en-us/gallery/", type: "article" }], completed: false },
    { id: "ds11", week: 11, topic: "Kaggle Competitions", description: "Feature engineering strategies, ensemble methods, and leaderboard climbing.", level: "Advanced", tasks: ["Enter a Kaggle competition and finish top 30%", "Build an XGBoost + LightGBM ensemble", "Write a detailed solution notebook"], resources: [{ title: "Kaggle Competitions", url: "https://www.kaggle.com/competitions", type: "course" }, { title: "Winning Kaggle Strategies", url: "https://www.kaggle.com/code/abhinand05/winning-a-kaggle-competition-in-less-than-two-hours", type: "article" }], completed: false },
    { id: "ds12", week: 12, topic: "Data Science Interview Prep", description: "SQL challenges, ML concepts, case studies, and portfolio polishing.", level: "Intermediate", tasks: ["Complete 30 SQL interview questions", "Practice 10 ML concept questions", "Publish a project to GitHub"], resources: [{ title: "Ace the Data Science Interview", url: "https://www.acethedatascienceinterview.com", type: "course" }, { title: "Stratascratch SQL Problems", url: "https://www.stratascratch.com", type: "course" }], completed: false },
  ],
  devops: [
    { id: "dv1", week: 1, topic: "Docker & Containerization", description: "Dockerfile, multi-stage builds, docker-compose, and container security.", level: "Beginner", tasks: ["Containerize a Node.js app", "Set up docker-compose for dev", "Scan image for vulnerabilities"], resources: [{ title: "Docker Official Getting Started", url: "https://docs.docker.com/get-started/", type: "article" }, { title: "Play with Docker", url: "https://labs.play-with-docker.com", type: "course" }], completed: false },
    { id: "dv2", week: 2, topic: "Kubernetes Fundamentals", description: "Pods, deployments, services, configmaps, and Helm charts.", level: "Intermediate", tasks: ["Deploy an app to a local k8s cluster", "Set up health checks and rolling updates", "Write a Helm chart"], resources: [{ title: "Kubernetes.io Tutorials", url: "https://kubernetes.io/docs/tutorials/", type: "article" }, { title: "KodeKloud CKA Course", url: "https://kodekloud.com/courses/certified-kubernetes-administrator-cka/", type: "course" }], completed: false },
    { id: "dv3", week: 3, topic: "CI/CD Pipelines", description: "GitHub Actions, GitLab CI, Jenkins, and automated testing gates.", level: "Intermediate", tasks: ["Build a full CI/CD pipeline", "Add automated tests as gates", "Implement PR-based deployments"], resources: [{ title: "GitHub Actions Docs", url: "https://docs.github.com/en/actions", type: "article" }, { title: "GitLab CI Tutorial", url: "https://docs.gitlab.com/ee/ci/quick_start/", type: "article" }], completed: false },
    { id: "dv4", week: 4, topic: "Infrastructure as Code with Terraform", description: "Terraform modules, state management, and cloud provider APIs.", level: "Intermediate", tasks: ["Provision AWS VPC and EC2 with Terraform", "Write reusable Terraform modules", "Manage state with S3 backend"], resources: [{ title: "Terraform Getting Started", url: "https://developer.hashicorp.com/terraform/tutorials", type: "course" }, { title: "Terraform Best Practices", url: "https://www.terraform-best-practices.com", type: "article" }], completed: false },
    { id: "dv5", week: 5, topic: "Cloud Platforms — AWS", description: "EC2, S3, RDS, IAM, Lambda, and cost optimization.", level: "Intermediate", tasks: ["Pass AWS Cloud Practitioner practice exam", "Deploy a 3-tier app on AWS", "Set up IAM roles with least privilege"], resources: [{ title: "AWS Free Tier Training", url: "https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/", type: "course" }, { title: "A Cloud Guru AWS Path", url: "https://www.pluralsight.com/cloud-guru", type: "course" }], completed: false },
    { id: "dv6", week: 6, topic: "Observability & Monitoring", description: "Prometheus, Grafana, alerting, SLOs, and distributed tracing.", level: "Advanced", tasks: ["Set up Prometheus + Grafana dashboards", "Define SLOs and error budgets", "Add tracing with OpenTelemetry"], resources: [{ title: "Prometheus Getting Started", url: "https://prometheus.io/docs/prometheus/latest/getting_started/", type: "article" }, { title: "Google SRE Book (free)", url: "https://sre.google/sre-book/table-of-contents/", type: "article" }], completed: false },
    { id: "dv7", week: 7, topic: "Security in DevOps (DevSecOps)", description: "SAST/DAST, secrets management, and SBOM scanning.", level: "Advanced", tasks: ["Integrate Snyk into CI pipeline", "Set up Vault for secrets management", "Run a DAST scan with OWASP ZAP"], resources: [{ title: "OWASP DevSecOps Guideline", url: "https://owasp.org/www-project-devsecops-guideline/", type: "article" }, { title: "HashiCorp Vault Tutorial", url: "https://developer.hashicorp.com/vault/tutorials", type: "course" }], completed: false },
    { id: "dv8", week: 8, topic: "Service Mesh & Networking", description: "Istio, Envoy, network policies, and service-to-service security.", level: "Advanced", tasks: ["Deploy Istio on a k8s cluster", "Configure mutual TLS between services", "Implement traffic mirroring"], resources: [{ title: "Istio Getting Started", url: "https://istio.io/latest/docs/setup/getting-started/", type: "article" }, { title: "Kubernetes Networking Guide", url: "https://kubernetes.io/docs/concepts/cluster-administration/networking/", type: "article" }], completed: false },
    { id: "dv9", week: 9, topic: "GitOps with ArgoCD / Flux", description: "GitOps principles, ArgoCD setup, and automated rollbacks.", level: "Advanced", tasks: ["Set up ArgoCD for a project", "Implement automated rollbacks on failure", "Create environment promotion pipelines"], resources: [{ title: "ArgoCD Getting Started", url: "https://argo-cd.readthedocs.io/en/stable/getting_started/", type: "article" }, { title: "Flux GitOps Docs", url: "https://fluxcd.io/flux/get-started/", type: "article" }], completed: false },
    { id: "dv10", week: 10, topic: "Incident Management & SRE", description: "On-call rotations, runbooks, blameless postmortems, and SLAs.", level: "Advanced", tasks: ["Write runbooks for 5 failure modes", "Conduct a simulated game day", "Create a postmortem template"], resources: [{ title: "Google SRE Workbook", url: "https://sre.google/workbook/table-of-contents/", type: "article" }, { title: "PagerDuty Incident Response Guide", url: "https://response.pagerduty.com", type: "article" }], completed: false },
    { id: "dv11", week: 11, topic: "Platform Engineering", description: "Internal developer platforms, golden paths, and developer experience.", level: "Advanced", tasks: ["Design an internal developer platform", "Implement a service catalog", "Build a self-service provisioning flow"], resources: [{ title: "CNCF Platform Engineering Whitepaper", url: "https://tag-app-delivery.cncf.io/whitepapers/platforms/", type: "article" }, { title: "Backstage Developer Portal", url: "https://backstage.io/docs/overview/what-is-backstage/", type: "article" }], completed: false },
    { id: "dv12", week: 12, topic: "DevOps Interview Prep", description: "System design for infrastructure, behavioral questions, and certifications.", level: "Intermediate", tasks: ["Practice 5 cloud architecture design questions", "Review CKA exam topics", "Write answers to 10 DevOps behavioral questions"], resources: [{ title: "DevOps Interview Questions", url: "https://www.interviewbit.com/devops-interview-questions/", type: "article" }, { title: "CKA Study Guide", url: "https://github.com/cncf/curriculum", type: "article" }], completed: false },
  ],
  "full stack": [
    { id: "fs1", week: 1, topic: "Frontend Foundations with React", description: "React, TypeScript, state management, and modern CSS.", level: "Beginner", tasks: ["Build a React + TypeScript CRUD app", "Add React Query for data fetching", "Style with Tailwind CSS"], resources: [{ title: "React + TypeScript Cheatsheet", url: "https://react-typescript-cheatsheet.netlify.app", type: "article" }, { title: "TanStack Query Docs", url: "https://tanstack.com/query", type: "article" }], completed: false },
    { id: "fs2", week: 2, topic: "Backend & REST APIs", description: "Node.js/Express APIs, middleware, error handling, and validation.", level: "Intermediate", tasks: ["Build a REST API with Express", "Add request validation with Zod", "Implement proper error handling middleware"], resources: [{ title: "Node.js Best Practices", url: "https://github.com/goldbergyoni/nodebestpractices", type: "article" }, { title: "Express.js Guide", url: "https://expressjs.com/en/guide/routing.html", type: "article" }], completed: false },
    { id: "fs3", week: 3, topic: "Database Design", description: "PostgreSQL, schema design, ORM, and migrations.", level: "Intermediate", tasks: ["Design a normalized schema for a blog", "Implement CRUD with Drizzle ORM", "Write reversible migrations"], resources: [{ title: "Drizzle ORM Docs", url: "https://orm.drizzle.team", type: "article" }, { title: "PostgreSQL Tutorial", url: "https://www.postgresqltutorial.com", type: "article" }], completed: false },
    { id: "fs4", week: 4, topic: "Authentication & Authorization", description: "Sessions, JWT, OAuth2, and role-based access control.", level: "Intermediate", tasks: ["Implement JWT authentication", "Add Google OAuth via Passport.js", "Build RBAC middleware"], resources: [{ title: "Auth0 JWT Guide", url: "https://auth0.com/learn/json-web-tokens", type: "article" }, { title: "Passport.js Docs", url: "https://www.passportjs.org/docs/", type: "article" }], completed: false },
    { id: "fs5", week: 5, topic: "API Design Patterns", description: "REST vs GraphQL, pagination, filtering, and versioning.", level: "Intermediate", tasks: ["Add cursor-based pagination to an API", "Implement filtering and sorting", "Design a GraphQL schema"], resources: [{ title: "GraphQL Docs", url: "https://graphql.org/learn/", type: "article" }, { title: "API Pagination Best Practices", url: "https://www.freecodecamp.org/news/the-ultimate-guide-to-api-pagination-in-rest-and-graphql/", type: "article" }], completed: false },
    { id: "fs6", week: 6, topic: "Caching & Performance", description: "Redis, CDN caching, query optimization, and N+1 problems.", level: "Advanced", tasks: ["Add Redis caching to an API", "Fix N+1 queries with eager loading", "Set up CDN for static assets"], resources: [{ title: "Redis University RU101", url: "https://university.redis.com/courses/ru101/", type: "course" }, { title: "Web Performance Optimization", url: "https://web.dev/performance", type: "article" }], completed: false },
    { id: "fs7", week: 7, topic: "Real-Time Features", description: "WebSockets, Server-Sent Events, and real-time notifications.", level: "Advanced", tasks: ["Build a real-time chat with Socket.io", "Add live notifications with SSE", "Implement presence indicators"], resources: [{ title: "Socket.io Docs", url: "https://socket.io/docs/v4/", type: "article" }, { title: "WebSockets MDN Guide", url: "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API", type: "article" }], completed: false },
    { id: "fs8", week: 8, topic: "File Uploads & Storage", description: "Multipart uploads, S3/Cloudinary, image processing, and CDN delivery.", level: "Intermediate", tasks: ["Build a file upload API with S3", "Implement image resizing with Sharp", "Add drag-and-drop file UI"], resources: [{ title: "AWS S3 Developer Guide", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html", type: "article" }, { title: "Cloudinary Docs", url: "https://cloudinary.com/documentation", type: "article" }], completed: false },
    { id: "fs9", week: 9, topic: "Testing Full Stack Apps", description: "Unit, integration, and E2E testing across frontend and backend.", level: "Intermediate", tasks: ["Write API integration tests with Supertest", "Add E2E tests with Playwright", "Achieve 75% overall coverage"], resources: [{ title: "Supertest Docs", url: "https://github.com/ladjs/supertest", type: "article" }, { title: "Playwright Docs", url: "https://playwright.dev/docs/intro", type: "article" }], completed: false },
    { id: "fs10", week: 10, topic: "Deployment & DevOps", description: "Docker, CI/CD, cloud hosting, and environment management.", level: "Intermediate", tasks: ["Dockerize the full stack app", "Set up GitHub Actions CI/CD", "Deploy to Railway/Render/Fly.io"], resources: [{ title: "Docker Docs", url: "https://docs.docker.com", type: "article" }, { title: "GitHub Actions Docs", url: "https://docs.github.com/en/actions", type: "article" }], completed: false },
    { id: "fs11", week: 11, topic: "System Design for Full Stack", description: "Scalability, microservices, event-driven architecture, and API gateways.", level: "Advanced", tasks: ["Design a scalable URL shortener", "Sketch a microservices architecture", "Plan a database sharding strategy"], resources: [{ title: "System Design Primer", url: "https://github.com/donnemartin/system-design-primer", type: "article" }, { title: "Grokking System Design", url: "https://www.designgurus.io/course/grokking-the-system-design-interview", type: "course" }], completed: false },
    { id: "fs12", week: 12, topic: "Portfolio & Interview Prep", description: "Build a showcase project, practice system design, and behavioral prep.", level: "Beginner", tasks: ["Build and deploy a full portfolio project", "Record a 10-min demo walkthrough", "Practice 5 full stack interview scenarios"], resources: [{ title: "Full Stack Open Course", url: "https://fullstackopen.com/en/", type: "course" }, { title: "Fullstack Interview Handbook", url: "https://www.techinterviewhandbook.org/software-engineering-interview-guide/", type: "article" }], completed: false },
  ],
  mobile: [
    { id: "mb1", week: 1, topic: "React Native & Expo Foundations", description: "Navigation, layouts, platform differences, and native modules.", level: "Beginner", tasks: ["Build a tab-based app", "Implement stack navigation", "Handle iOS/Android differences"], resources: [{ title: "Expo Docs", url: "https://docs.expo.dev", type: "article" }, { title: "React Native Express", url: "https://www.reactnativeexpress.com", type: "article" }], completed: false },
    { id: "mb2", week: 2, topic: "Core UI Components", description: "FlatList, ScrollView, TextInput, and platform-specific components.", level: "Beginner", tasks: ["Build a virtualized list with 500+ items", "Implement pull-to-refresh", "Create platform-specific UI variants"], resources: [{ title: "React Native Core Components", url: "https://reactnative.dev/docs/components-and-apis", type: "article" }, { title: "React Native Community", url: "https://reactnativecommunity.github.io", type: "article" }], completed: false },
    { id: "mb3", week: 3, topic: "State & Data Management", description: "Context API, Zustand, React Query, and AsyncStorage.", level: "Intermediate", tasks: ["Implement offline-first storage", "Add optimistic UI updates", "Handle network state changes"], resources: [{ title: "TanStack Query for React Native", url: "https://tanstack.com/query/latest/docs/react/overview", type: "article" }, { title: "Zustand Docs", url: "https://zustand-demo.pmnd.rs", type: "article" }], completed: false },
    { id: "mb4", week: 4, topic: "Expo Router & Navigation", description: "File-based routing, deep linking, and tab/stack navigation.", level: "Intermediate", tasks: ["Set up file-based routing with Expo Router", "Implement deep linking", "Build a complex navigation flow"], resources: [{ title: "Expo Router Docs", url: "https://docs.expo.dev/router/introduction/", type: "article" }, { title: "React Navigation Docs", url: "https://reactnavigation.org/docs/getting-started", type: "article" }], completed: false },
    { id: "mb5", week: 5, topic: "Animations & Gestures", description: "Reanimated 3, gesture handler, and micro-interactions.", level: "Advanced", tasks: ["Build a swipe-to-delete gesture", "Create a shared element transition", "Implement spring physics animations"], resources: [{ title: "Reanimated Docs", url: "https://docs.swmansion.com/react-native-reanimated/", type: "article" }, { title: "React Native Gesture Handler Docs", url: "https://docs.swmansion.com/react-native-gesture-handler/", type: "article" }], completed: false },
    { id: "mb6", week: 6, topic: "Native Device Features", description: "Camera, location, contacts, notifications, and biometrics.", level: "Intermediate", tasks: ["Build a photo picker with camera support", "Implement location tracking", "Add push notifications with Expo"], resources: [{ title: "Expo Camera Docs", url: "https://docs.expo.dev/versions/latest/sdk/camera/", type: "article" }, { title: "Expo Location Docs", url: "https://docs.expo.dev/versions/latest/sdk/location/", type: "article" }], completed: false },
    { id: "mb7", week: 7, topic: "Performance Optimization", description: "FlatList virtualization, memo, useMemo, and profiling.", level: "Advanced", tasks: ["Optimize FlatList with 1000+ items using getItemLayout", "Eliminate unnecessary re-renders with memo", "Profile with Flipper DevTools"], resources: [{ title: "React Native Performance Docs", url: "https://reactnative.dev/docs/performance", type: "article" }, { title: "React Native Profiler Tutorial", url: "https://www.youtube.com/watch?v=IyCI0sy0ZSM", type: "video" }], completed: false },
    { id: "mb8", week: 8, topic: "Networking & API Integration", description: "REST APIs, GraphQL, WebSockets, and error handling.", level: "Intermediate", tasks: ["Build a data fetching layer with React Query", "Add offline sync with background fetch", "Handle API errors gracefully"], resources: [{ title: "Axios Docs", url: "https://axios-http.com/docs/intro", type: "article" }, { title: "React Native Offline First", url: "https://medium.com/sensehq/offline-first-react-native-app-using-apollo-and-redux-offline-4addf3ad6117", type: "article" }], completed: false },
    { id: "mb9", week: 9, topic: "Styling & Design Systems", description: "StyleSheet, styled-components, Tamagui, and NativeWind.", level: "Intermediate", tasks: ["Build a theming system with dark/light mode", "Create a reusable component library", "Implement NativeWind styling"], resources: [{ title: "NativeWind Docs", url: "https://www.nativewind.dev", type: "article" }, { title: "Tamagui Docs", url: "https://tamagui.dev/docs/intro/introduction", type: "article" }], completed: false },
    { id: "mb10", week: 10, topic: "Testing Mobile Apps", description: "Jest, React Native Testing Library, and Detox E2E tests.", level: "Intermediate", tasks: ["Write 20 unit tests with RNTL", "Add E2E tests with Detox", "Test gestures and animations"], resources: [{ title: "React Native Testing Library Docs", url: "https://callstack.github.io/react-native-testing-library/", type: "article" }, { title: "Detox Testing Framework", url: "https://wix.github.io/Detox/", type: "article" }], completed: false },
    { id: "mb11", week: 11, topic: "App Store Preparation", description: "EAS Build, app signing, screenshots, and App Store guidelines.", level: "Advanced", tasks: ["Set up EAS Build for iOS & Android", "Create App Store screenshots in 5 sizes", "Write a compelling App Store description"], resources: [{ title: "EAS Build Docs", url: "https://docs.expo.dev/build/introduction/", type: "article" }, { title: "App Store Review Guidelines", url: "https://developer.apple.com/app-store/review/guidelines/", type: "article" }], completed: false },
    { id: "mb12", week: 12, topic: "Mobile Interview Prep", description: "Mobile-specific interview questions, portfolio, and live coding.", level: "Intermediate", tasks: ["Build a polished demo app for interviews", "Practice 10 React Native interview questions", "Prepare a mobile architecture walkthrough"], resources: [{ title: "React Native Interview Questions", url: "https://www.interviewbit.com/react-native-interview-questions/", type: "article" }, { title: "Expo Showcase", url: "https://expo.dev/gallery", type: "article" }], completed: false },
  ],
  default: [
    { id: "d1", week: 1, topic: "Data Structures & Algorithms", description: "Arrays, hash maps, trees, and graphs. Master the interview fundamentals.", level: "Beginner", tasks: ["Complete LeetCode Easy 25 problems", "Study array and hash map patterns", "Practice time/space complexity analysis"], resources: [{ title: "LeetCode Top 150", url: "https://leetcode.com/studyplan/top-interview-150/", type: "course" }, { title: "NeetCode Roadmap", url: "https://neetcode.io/roadmap", type: "video" }], completed: false },
    { id: "d2", week: 2, topic: "System Design Fundamentals", description: "Scalability, databases, caching, and distributed system patterns.", level: "Intermediate", tasks: ["Design 3 systems from scratch", "Study CAP theorem", "Practice estimation problems"], resources: [{ title: "System Design Primer", url: "https://github.com/donnemartin/system-design-primer", type: "article" }, { title: "Grokking the System Design Interview", url: "https://www.designgurus.io/course/grokking-the-system-design-interview", type: "course" }], completed: false },
    { id: "d3", week: 3, topic: "Behavioral Interview Mastery", description: "STAR method, leadership principles, and conflict resolution.", level: "Intermediate", tasks: ["Write 10 STAR stories", "Record yourself answering 5 questions", "Study Amazon Leadership Principles"], resources: [{ title: "Amazon LP Guide", url: "https://www.amazon.jobs/content/en/our-workplace/leadership-principles", type: "article" }, { title: "STAR Method Masterclass", url: "https://www.themuse.com/advice/star-interview-method", type: "article" }], completed: false },
    { id: "d4", week: 4, topic: "Resume & Portfolio Polish", description: "ATS optimization, GitHub profile, and LinkedIn presence.", level: "Beginner", tasks: ["Optimize CV with action verbs + metrics", "Pin 3 projects on GitHub", "Update LinkedIn with quantified achievements"], resources: [{ title: "Levels.fyi Resume Guide", url: "https://www.levels.fyi/blog/swe-resume-guide.html", type: "article" }, { title: "GitHub Profile README Guide", url: "https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile", type: "article" }], completed: false },
    { id: "d5", week: 5, topic: "Networking & Job Applications", description: "LinkedIn outreach, referrals, and cold emailing strategies.", level: "Beginner", tasks: ["Send 20 personalized LinkedIn connection requests", "Get 3 referrals from your network", "Apply to 15 targeted jobs"], resources: [{ title: "LinkedIn Job Hunting Guide", url: "https://www.linkedin.com/learning/job-search-strategies/", type: "course" }, { title: "Cold Email Templates for Jobs", url: "https://www.themuse.com/advice/how-to-cold-email-for-a-job", type: "article" }], completed: false },
    { id: "d6", week: 6, topic: "Technical Interview Patterns", description: "Two pointers, sliding window, dynamic programming, and BFS/DFS.", level: "Intermediate", tasks: ["Solve 15 medium LeetCode problems", "Master 5 common interview patterns", "Complete the Blind 75 list"], resources: [{ title: "Blind 75 List", url: "https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions", type: "article" }, { title: "NeetCode 150 Videos", url: "https://neetcode.io/practice", type: "video" }], completed: false },
    { id: "d7", week: 7, topic: "Salary Negotiation", description: "Market research, negotiation tactics, and equity understanding.", level: "Beginner", tasks: ["Research market salaries on Levels.fyi", "Practice negotiation role-play", "Learn to evaluate equity packages"], resources: [{ title: "Levels.fyi Compensation Data", url: "https://www.levels.fyi", type: "article" }, { title: "Patrick McKenzie on Salary Negotiation", url: "https://www.kalzumeus.com/2012/01/23/salary-negotiation/", type: "article" }], completed: false },
    { id: "d8", week: 8, topic: "Side Projects & Open Source", description: "Building portfolio projects and contributing to open source.", level: "Intermediate", tasks: ["Complete one side project end-to-end", "Submit a PR to an open source project", "Write a technical blog post"], resources: [{ title: "GitHub Good First Issues", url: "https://goodfirstissue.dev", type: "article" }, { title: "Dev.to for Tech Writing", url: "https://dev.to", type: "article" }], completed: false },
    { id: "d9", week: 9, topic: "Communication & Writing", description: "Technical writing, documentation, and presentation skills.", level: "Beginner", tasks: ["Write a technical README for a project", "Give a 5-min tech talk to friends", "Document an API you built"], resources: [{ title: "Google Technical Writing Course", url: "https://developers.google.com/tech-writing", type: "course" }, { title: "Toastmasters Find a Club", url: "https://www.toastmasters.org/find-a-club", type: "article" }], completed: false },
    { id: "d10", week: 10, topic: "Code Reviews & Team Collaboration", description: "Effective code reviews, pull request etiquette, and pair programming.", level: "Intermediate", tasks: ["Review 5 open source PRs", "Write a coding style guide", "Pair program for one session"], resources: [{ title: "Google Code Review Guide", url: "https://google.github.io/eng-practices/review/", type: "article" }, { title: "How to Do Code Reviews Like a Human", url: "https://mtlynch.io/human-code-reviews-1/", type: "article" }], completed: false },
    { id: "d11", week: 11, topic: "Mock Interviews", description: "Practice technical and behavioral interviews with real feedback.", level: "Intermediate", tasks: ["Complete 5 mock interviews on Pramp", "Record 3 mock technical interviews", "Get feedback from a senior engineer"], resources: [{ title: "Pramp Mock Interviews (free)", url: "https://www.pramp.com", type: "course" }, { title: "Interviewing.io Practice", url: "https://interviewing.io", type: "course" }], completed: false },
    { id: "d12", week: 12, topic: "Final Prep & Offers", description: "Final preparation, offer evaluation, and first-week success tips.", level: "Beginner", tasks: ["Apply to 30 companies this week", "Complete final system design review", "Prepare your first-day onboarding questions"], resources: [{ title: "Tech Interview Handbook", url: "https://www.techinterviewhandbook.org", type: "article" }, { title: "The First 90 Days Guide", url: "https://www.amazon.com/First-Days-Updated-Expanded-Strategies/dp/1422188612", type: "article" }], completed: false },
  ],
};

function getRoleTemplate(role: string): RoadmapModule[] {
  const normalized = role.toLowerCase();
  if (normalized.includes("frontend") || normalized.includes("react") || normalized.includes("ui")) return ROLE_ROADMAPS.frontend;
  if (normalized.includes("backend") || normalized.includes("node") || normalized.includes("api")) return ROLE_ROADMAPS.backend;
  if (normalized.includes("data science") || normalized.includes("ml") || normalized.includes("machine learning") || normalized.includes("ai")) return ROLE_ROADMAPS["data science"];
  if (normalized.includes("devops") || normalized.includes("sre") || normalized.includes("cloud") || normalized.includes("platform")) return ROLE_ROADMAPS.devops;
  if (normalized.includes("full stack") || normalized.includes("fullstack")) return ROLE_ROADMAPS["full stack"];
  if (normalized.includes("mobile") || normalized.includes("react native") || normalized.includes("ios") || normalized.includes("android")) return ROLE_ROADMAPS.mobile;
  return ROLE_ROADMAPS.default;
}

const RoadmapContext = createContext<RoadmapContextType | null>(null);

export function RoadmapProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const load = useCallback(async () => {
    if (!user) { setRoadmap(null); return; }
    const data = await AsyncStorage.getItem(`roadmap_${user.id}`);
    if (data) setRoadmap(JSON.parse(data));
    else setRoadmap(null);
  }, [user]);

  useEffect(() => { load(); }, [load]);

  const generateRoadmap = async (skillGaps: string[], targetRole: string, experienceLevel = "Mid") => {
    if (!user) return;
    setIsGenerating(true);
    try {
      let modules = getRoleTemplate(targetRole);
      const apiKey = process.env.EXPO_PUBLIC_OPENAI_API_KEY;

      if (apiKey && skillGaps.length > 0) {
        try {
          const levelMap: Record<string, string> = { Student: "Beginner", "Entry-level": "Beginner", "Mid-level": "Intermediate", Senior: "Advanced", "Lead/Principal": "Advanced" };
          const level = levelMap[experienceLevel] || "Intermediate";
          const prompt = `Create a 12-week role-specific upskilling roadmap for a ${targetRole} (${level} level).
Skill gaps: ${skillGaps.join(", ")}
Return JSON: { modules: [{ id, week: 1-12, topic, description, level: "Beginner"|"Intermediate"|"Advanced", tasks: ["3 specific tasks"], resources: [{ title, url, type: "video"|"article"|"course" }], completed: false }] }
- Each module addresses specific skill gaps for ${targetRole}
- Include 2 real, working URLs per module
- Tasks should be concrete and actionable`;
          const res = await fetch("https://api.openai.com/v1/chat/completions", {
            method: "POST",
            headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` },
            body: JSON.stringify({ model: "gpt-4o-mini", messages: [{ role: "user", content: prompt }], response_format: { type: "json_object" } }),
          });
          const json = await res.json();
          const parsed = JSON.parse(json.choices[0].message.content);
          if (Array.isArray(parsed.modules) && parsed.modules.length >= 4) modules = parsed.modules;
        } catch { /* use template */ }
      }

      const newRoadmap: Roadmap = { id: Date.now().toString(), userId: user.id, title: `12-Week ${targetRole} Roadmap`, role: targetRole, level: experienceLevel, modules, createdAt: new Date().toISOString() };
      await AsyncStorage.setItem(`roadmap_${user.id}`, JSON.stringify(newRoadmap));
      setRoadmap(newRoadmap);
    } finally {
      setIsGenerating(false);
    }
  };

  const toggleModule = async (moduleId: string) => {
    if (!roadmap || !user) return;
    const updated: Roadmap = { ...roadmap, modules: roadmap.modules.map((m) => m.id === moduleId ? { ...m, completed: !m.completed } : m) };
    await AsyncStorage.setItem(`roadmap_${user.id}`, JSON.stringify(updated));
    setRoadmap(updated);
  };

  const clearRoadmap = async () => {
    if (!user) return;
    await AsyncStorage.removeItem(`roadmap_${user.id}`);
    setRoadmap(null);
  };

  return (
    <RoadmapContext.Provider value={{ roadmap, isGenerating, generateRoadmap, toggleModule, clearRoadmap }}>
      {children}
    </RoadmapContext.Provider>
  );
}

export function useRoadmap() {
  const ctx = useContext(RoadmapContext);
  if (!ctx) throw new Error("useRoadmap must be used within RoadmapProvider");
  return ctx;
}
