import {
  FileText,
  GraduationCap,
  Briefcase,
  Download,
  ClipboardCopy,
  CheckCircle,
  Upload,
  AlertCircle,
  X,
  Zap,
  ChevronDown,
  MapPin,
  Wrench,
  Lightbulb,
} from "lucide-react-native";
import * as Haptics from "expo-haptics";
import * as Clipboard from "expo-clipboard";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system";
import React, { useState } from "react";
import {
  ActivityIndicator,
  Alert,
  LayoutAnimation,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { ScoreRing } from "@/components/ScoreRing";
import { useCV, ATSBreakdown } from "@/context/CVContext";
import { useAuth } from "@/context/AuthContext";
import { useColors } from "@/hooks/useColors";
import { extractPdfTextFromBase64 } from "@/utils/pdfExtract";

type CVFormat = "Harvard" | "MIT" | "Corporate";
const CV_FORMATS: { id: CVFormat; label: string; icon: React.ElementType; description: string; color: string }[] = [
  { id: "Harvard", label: "Harvard", icon: GraduationCap, description: "Academic, achievement-focused", color: "#A51C30" },
  { id: "MIT", label: "MIT", icon: FileText, description: "Technical, projects-first", color: "#750014" },
  { id: "Corporate", label: "Corporate", icon: Briefcase, description: "Experience-first, metric-driven", color: "#1a56db" },
];

const BREAKDOWN_ROWS: { key: keyof ATSBreakdown; label: string; weight: string }[] = [
  { key: "keyword", label: "Keyword Optimisation", weight: "20%" },
  { key: "formatting", label: "Formatting & Structure", weight: "15%" },
  { key: "achievements", label: "Quantifiable Achievements", weight: "20%" },
  { key: "skills", label: "Skills Presentation", weight: "15%" },
  { key: "experience", label: "Experience Relevance", weight: "15%" },
  { key: "grammar", label: "Grammar & Spelling", weight: "15%" },
];

function generatePDFHTML(cvText: string, userName: string): string {
  const escaped = cvText.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\n/g, "<br/>");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/><style>body{font-family:Georgia,serif;font-size:12pt;line-height:1.6;margin:40px;color:#1a1a1a;}pre{white-space:pre-wrap;font-family:Georgia,serif;font-size:12pt;}</style></head><body><pre>${escaped}</pre><p style="color:#999;font-size:9pt;text-align:center;margin-top:40px;">Generated by CareerAI · ${new Date().toLocaleDateString()}</p></body></html>`;
}

export default function CVScreen() {
  const colors = useColors() as any;
  const cvColor = colors.cv || colors.primary;
  const insets = useSafeAreaInsets();
  const { user } = useAuth();
  const { cvProfile, isAnalyzing, analyzeCV, clearCV } = useCV();
  const [activeTab, setActiveTab] = useState<"input" | "result">("input");
  const [selectedFormat, setSelectedFormat] = useState<CVFormat>("Harvard");
  const [isCopied, setIsCopied] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [pdfFileName, setPdfFileName] = useState<string | null>(null);
  const [pdfError, setPdfError] = useState<string | null>(null);
  const [isPickingPdf, setIsPickingPdf] = useState(false);
  const [expandedSuggestion, setExpandedSuggestion] = useState<number | null>(0);
  const topPad = Platform.OS === "web" ? 67 : insets.top;
  const bottomPad = Platform.OS === "web" ? 34 : insets.bottom;

  const toggleSuggestion = (index: number) => {
    LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
    setExpandedSuggestion((prev) => (prev === index ? null : index));
  };

  const handlePickPDF = async () => {
    setPdfError(null);
    setIsPickingPdf(true);
    try {
      const result = await DocumentPicker.getDocumentAsync({ type: "application/pdf", copyToCacheDirectory: true });
      if (result.canceled || !result.assets?.length) return;
      const asset = result.assets[0];
      if (!asset.name.toLowerCase().endsWith(".pdf")) {
        setPdfError("Please upload a PDF file");
        return;
      }
      setPdfFileName(asset.name);
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);

      let extractedText = "";
      try {
        const base64 = await FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.Base64 });
        extractedText = extractPdfTextFromBase64(base64);
      } catch {
        /* fall through to error below */
      }

      if (!extractedText || extractedText.trim().length < 40) {
        setPdfError("Couldn't read text from this PDF. Please upload a text-based PDF (not a scanned image).");
        setIsPickingPdf(false);
        return;
      }

      await analyzeCV(extractedText, selectedFormat);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      setExpandedSuggestion(0);
      setActiveTab("result");
    } catch (err: any) {
      setPdfError("Failed to read the PDF. Please try again.");
    } finally {
      setIsPickingPdf(false);
    }
  };

  const handleClear = () => {
    Alert.alert("Clear CV", "Remove current CV analysis?", [
      { text: "Cancel", style: "cancel" },
      { text: "Clear", style: "destructive", onPress: () => { clearCV(); setPdfFileName(null); setPdfError(null); setActiveTab("input"); } },
    ]);
  };

  const handleCopyToClipboard = async () => {
    const text = cvProfile?.fullOptimizedCV || "";
    if (!text) return;
    try {
      await Clipboard.setStringAsync(text);
      setIsCopied(true);
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      setTimeout(() => setIsCopied(false), 3000);
    } catch { Alert.alert("Copy Failed", "Could not copy to clipboard."); }
  };

  const handleExportPDF = async () => {
    const text = cvProfile?.fullOptimizedCV || "";
    if (!text) return;
    setIsExporting(true);
    try {
      const html = generatePDFHTML(text, user?.name || "");
      if (Platform.OS === "web") {
        const blob = new Blob([html], { type: "text/html" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url; a.download = "optimized-cv.html"; a.click();
        URL.revokeObjectURL(url);
      } else {
        const { uri } = await Print.printToFileAsync({ html });
        if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: "application/pdf" });
        else await Print.printAsync({ html });
      }
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch { Alert.alert("Export Failed", "Could not generate PDF."); }
    finally { setIsExporting(false); }
  };

  return (
    <View style={[styles.container, { backgroundColor: colors.background }]}>
      <View style={[styles.header, { paddingTop: topPad + 16, borderBottomColor: colors.border, backgroundColor: colors.card }]}>
        <Text style={[styles.headerTitle, { color: colors.foreground }]}>CV Engine</Text>
        <Text style={[styles.headerSub, { color: colors.mutedForeground }]}>Upload PDF · AI optimisation · ATS scoring</Text>
      </View>

      {cvProfile && (
        <View style={[styles.tabBar, { backgroundColor: colors.muted }]}>
          {(["input", "result"] as const).map((tab) => (
            <TouchableOpacity key={tab} style={[styles.tab, activeTab === tab && { backgroundColor: colors.card }]} onPress={() => setActiveTab(tab)}>
              <Text style={[styles.tabText, { color: activeTab === tab ? colors.foreground : colors.mutedForeground }]}>{tab === "input" ? "Upload" : "Results"}</Text>
            </TouchableOpacity>
          ))}
        </View>
      )}

      <ScrollView contentContainerStyle={{ padding: 24, paddingBottom: bottomPad + 100 }} showsVerticalScrollIndicator={false}>

        {(!cvProfile || activeTab === "input") && (
          <>
            <Text style={[styles.sectionTitle, { color: colors.foreground }]}>1. Choose CV Format</Text>
            <Text style={[styles.sectionSub, { color: colors.mutedForeground }]}>Select your format before uploading. AI will structure your CV accordingly.</Text>
            <View style={styles.formatRow}>
              {CV_FORMATS.map(({ id, label, icon: Icon, description, color }) => {
                const sel = selectedFormat === id;
                return (
                  <TouchableOpacity key={id} style={[styles.formatCard, { borderColor: sel ? color : colors.border, backgroundColor: sel ? color + "10" : colors.card }]} onPress={() => { setSelectedFormat(id); Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); }}>
                    <View style={[styles.formatIcon, { backgroundColor: color + "20" }]}><Icon size={18} color={color} /></View>
                    <Text style={[styles.formatLabel, { color: sel ? color : colors.foreground }]}>{label}</Text>
                    <Text style={[styles.formatDesc, { color: colors.mutedForeground }]}>{description}</Text>
                  </TouchableOpacity>
                );
              })}
            </View>

            <Text style={[styles.sectionTitle, { color: colors.foreground, marginTop: 4 }]}>2. Upload Your CV (PDF only)</Text>
            {pdfError && (
              <View style={[styles.errorBox, { backgroundColor: colors.destructive + "12", borderColor: colors.destructive + "30" }]}>
                <AlertCircle size={16} color={colors.destructive} />
                <Text style={[styles.errorText, { color: colors.destructive }]}>{pdfError}</Text>
                <TouchableOpacity onPress={() => setPdfError(null)}><X size={16} color={colors.destructive} /></TouchableOpacity>
              </View>
            )}

            <TouchableOpacity
              style={[styles.uploadZone, { borderColor: pdfFileName ? cvColor : colors.border, backgroundColor: pdfFileName ? cvColor + "08" : colors.card }]}
              onPress={handlePickPDF}
              disabled={isPickingPdf || isAnalyzing}
              activeOpacity={0.8}
            >
              {(isPickingPdf || isAnalyzing) ? (
                <>
                  <ActivityIndicator color={cvColor} size="large" />
                  <Text style={[styles.uploadTitle, { color: cvColor }]}>{isPickingPdf ? "Reading PDF…" : "Analysing CV…"}</Text>
                  <Text style={[styles.uploadSub, { color: colors.mutedForeground }]}>AI is extracting and optimising your CV</Text>
                </>
              ) : pdfFileName ? (
                <>
                  <View style={[styles.uploadIconCircle, { backgroundColor: cvColor + "20" }]}><CheckCircle size={32} color={cvColor} /></View>
                  <Text style={[styles.uploadTitle, { color: cvColor }]}>PDF Uploaded</Text>
                  <Text style={[styles.uploadFileName, { color: colors.foreground }]}>{pdfFileName}</Text>
                  <Text style={[styles.uploadSub, { color: colors.mutedForeground }]}>Tap to upload a different file</Text>
                </>
              ) : (
                <>
                  <View style={[styles.uploadIconCircle, { backgroundColor: colors.muted }]}><Upload size={32} color={colors.mutedForeground} /></View>
                  <Text style={[styles.uploadTitle, { color: colors.foreground }]}>Drag & drop your CV (PDF only)</Text>
                  <Text style={[styles.uploadSub, { color: colors.mutedForeground }]}>or click to browse</Text>
                  <View style={[styles.uploadBadge, { backgroundColor: colors.muted }]}><Text style={[styles.uploadBadgeText, { color: colors.mutedForeground }]}>Supported: .pdf</Text></View>
                </>
              )}
            </TouchableOpacity>

            <View style={[styles.infoBox, { backgroundColor: colors.accent, borderColor: colors.primary + "20" }]}>
              <Zap size={16} color={colors.primary} />
              <Text style={[styles.infoText, { color: colors.primary }]}>AI analyses your real CV content to give a precise ATS score breakdown, 5 Turnitin-style suggestions, and a fully optimised, complete CV in your chosen format.</Text>
            </View>
          </>
        )}

        {cvProfile && activeTab === "result" && (
          <>
            <View style={[styles.scoreRow, { backgroundColor: colors.card, borderColor: colors.border }]}>
              <ScoreRing score={cvProfile.atsScore} size={100} label="ATS Score" />
              <View style={{ flex: 1 }}>
                <Text style={[styles.scoreLabel, { color: colors.foreground }]}>
                  {cvProfile.atsScore >= 80 ? "Excellent" : cvProfile.atsScore >= 60 ? "Good" : "Needs Work"}
                </Text>
                <Text style={[styles.scoreNote, { color: colors.mutedForeground }]}>
                  {cvProfile.atsScore >= 80 ? "Your CV is ATS-ready and highly optimised." : cvProfile.atsScore >= 60 ? "Good foundation — apply the suggestions below to reach 80+." : "Significant improvements needed. Follow all suggestions carefully."}
                </Text>
              </View>
            </View>

            <Text style={[styles.sectionTitle, { color: colors.foreground }]}>ATS Score Breakdown</Text>
            <View style={[styles.breakdownCard, { backgroundColor: colors.card, borderColor: colors.border }]}>
              {BREAKDOWN_ROWS.map(({ key, label, weight }) => {
                const value = cvProfile.breakdown[key];
                const barColor = value >= 75 ? colors.success : value >= 50 ? colors.warning : colors.destructive;
                return (
                  <View key={key} style={styles.breakdownRow}>
                    <View style={styles.breakdownLabelRow}>
                      <Text style={[styles.breakdownLabel, { color: colors.foreground }]}>{label}</Text>
                      <Text style={[styles.breakdownWeight, { color: colors.mutedForeground }]}>{weight}</Text>
                      <Text style={[styles.breakdownValue, { color: barColor }]}>{value}%</Text>
                    </View>
                    <View style={[styles.barTrack, { backgroundColor: colors.muted }]}>
                      <View style={[styles.barFill, { width: `${value}%`, backgroundColor: barColor }]} />
                    </View>
                  </View>
                );
              })}
            </View>

            <Text style={[styles.sectionTitle, { color: colors.foreground }]}>AI Suggestions (tap to expand)</Text>
            {cvProfile.suggestions.map((s, i) => {
              const expanded = expandedSuggestion === i;
              return (
                <TouchableOpacity
                  key={i}
                  activeOpacity={0.85}
                  style={[styles.suggestionCard, { backgroundColor: colors.card, borderColor: expanded ? cvColor + "60" : colors.border }]}
                  onPress={() => toggleSuggestion(i)}
                >
                  <View style={styles.suggestionHeader}>
                    <View style={[styles.suggNum, { backgroundColor: cvColor + "20" }]}>
                      <AlertCircle size={16} color={cvColor} />
                    </View>
                    <Text style={[styles.suggTitle, { color: colors.foreground }]} numberOfLines={expanded ? undefined : 1}>
                      {i + 1}. {s.title}
                    </Text>
                    <ChevronDown
                      size={18}
                      color={colors.mutedForeground}
                      style={{ transform: [{ rotate: expanded ? "180deg" : "0deg" }] }}
                    />
                  </View>

                  {expanded && (
                    <View style={styles.suggestionBody}>
                      <View style={styles.suggDetailRow}>
                        <MapPin size={14} color={colors.mutedForeground} style={styles.suggDetailIcon} />
                        <Text style={[styles.suggDetailLabel, { color: colors.mutedForeground }]}>Location: </Text>
                        <Text style={[styles.suggDetailText, { color: colors.foreground }]}>{s.location}</Text>
                      </View>
                      <View style={styles.suggDetailRow}>
                        <AlertCircle size={14} color={colors.destructive} style={styles.suggDetailIcon} />
                        <Text style={[styles.suggDetailLabel, { color: colors.mutedForeground }]}>Problem: </Text>
                        <Text style={[styles.suggDetailText, { color: colors.foreground }]}>{s.problem}</Text>
                      </View>
                      <View style={styles.suggDetailRow}>
                        <Wrench size={14} color={colors.primary} style={styles.suggDetailIcon} />
                        <Text style={[styles.suggDetailLabel, { color: colors.mutedForeground }]}>Fix: </Text>
                        <Text style={[styles.suggDetailText, { color: colors.foreground }]}>{s.fix}</Text>
                      </View>
                      <View style={[styles.exampleBox, { backgroundColor: colors.accent }]}>
                        <Lightbulb size={14} color={colors.accentForeground || colors.primary} style={styles.suggDetailIcon} />
                        <Text style={[styles.suggDetailText, { color: colors.accentForeground || colors.primary, flex: 1 }]}>{s.example}</Text>
                      </View>
                    </View>
                  )}
                </TouchableOpacity>
              );
            })}

            <Text style={[styles.sectionTitle, { color: colors.foreground, marginTop: 8 }]}>Optimised CV ({cvProfile.format} Format · Full Content)</Text>
            <View style={[styles.optimizedBox, { backgroundColor: colors.card, borderColor: colors.border }]}>
              <Text style={[styles.optimizedText, { color: colors.foreground }]}>{cvProfile.fullOptimizedCV}</Text>
            </View>

            <View style={[styles.exportCard, { backgroundColor: colors.card, borderColor: colors.border }]}>
              <Text style={[styles.sectionTitle, { color: colors.foreground, marginBottom: 6 }]}>Download Updated CV</Text>
              <Text style={[styles.exportSubtitle, { color: colors.mutedForeground }]}>Full CV with all corrections applied — export as PDF or copy plain text.</Text>
              <View style={styles.exportRow}>
                <TouchableOpacity style={[styles.exportBtn, { backgroundColor: cvColor, opacity: isExporting ? 0.7 : 1 }]} onPress={handleExportPDF} disabled={isExporting}>
                  {isExporting ? <ActivityIndicator color="#fff" size="small" /> : <Download size={16} color="#fff" />}
                  <Text style={styles.exportBtnText}>PDF Download</Text>
                </TouchableOpacity>
                <TouchableOpacity style={[styles.exportBtn, { backgroundColor: "#2563eb" }]} onPress={handleCopyToClipboard}>
                  <ClipboardCopy size={16} color="#fff" />
                  <Text style={styles.exportBtnText}>Copy to Clipboard</Text>
                </TouchableOpacity>
              </View>
              {isCopied && (
                <View style={[styles.copiedBanner, { backgroundColor: "#2563eb15", borderColor: "#2563eb40" }]}>
                  <CheckCircle size={16} color="#2563eb" />
                  <Text style={[styles.copiedText, { color: "#2563eb" }]}>Full CV copied to clipboard!</Text>
                </View>
              )}
            </View>

            <TouchableOpacity style={[styles.clearBtn, { borderColor: colors.destructive + "50", backgroundColor: colors.card }]} onPress={handleClear}>
              <X size={18} color={colors.destructive} />
              <Text style={[styles.clearText, { color: colors.destructive }]}>Clear & Re-upload</Text>
            </TouchableOpacity>
          </>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  header: { paddingHorizontal: 24, paddingBottom: 16, borderBottomWidth: StyleSheet.hairlineWidth },
  headerTitle: { fontSize: 24, fontFamily: "Inter_700Bold", letterSpacing: -0.5 },
  headerSub: { fontSize: 14, fontFamily: "Inter_500Medium", marginTop: 4 },
  tabBar: { flexDirection: "row", marginHorizontal: 24, marginTop: 16, borderRadius: 12, padding: 4 },
  tab: { flex: 1, paddingVertical: 10, borderRadius: 8, alignItems: "center" },
  tabText: { fontFamily: "Inter_600SemiBold", fontSize: 14 },
  sectionTitle: { fontSize: 17, fontFamily: "Inter_700Bold", marginBottom: 6, letterSpacing: -0.3 },
  sectionSub: { fontSize: 13, fontFamily: "Inter_500Medium", marginBottom: 16, lineHeight: 20 },
  formatRow: { flexDirection: "row", gap: 10, marginBottom: 24 },
  formatCard: { flex: 1, borderRadius: 14, padding: 12, borderWidth: 1.5, alignItems: "center", gap: 6 },
  formatIcon: { width: 36, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  formatLabel: { fontFamily: "Inter_700Bold", fontSize: 13 },
  formatDesc: { fontFamily: "Inter_500Medium", fontSize: 11, textAlign: "center", lineHeight: 14 },
  errorBox: { flexDirection: "row", alignItems: "center", gap: 8, padding: 12, borderRadius: 12, borderWidth: 1, marginBottom: 16 },
  errorText: { flex: 1, fontSize: 13, fontFamily: "Inter_500Medium" },
  uploadZone: { borderRadius: 20, borderWidth: 2, borderStyle: "dashed", padding: 40, alignItems: "center", gap: 12, marginBottom: 20 },
  uploadIconCircle: { width: 72, height: 72, borderRadius: 36, alignItems: "center", justifyContent: "center", marginBottom: 4 },
  uploadTitle: { fontSize: 18, fontFamily: "Inter_700Bold", letterSpacing: -0.3, textAlign: "center" },
  uploadFileName: { fontSize: 14, fontFamily: "Inter_600SemiBold", textAlign: "center" },
  uploadSub: { fontSize: 13, fontFamily: "Inter_500Medium", textAlign: "center", lineHeight: 20 },
  uploadBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, marginTop: 4 },
  uploadBadgeText: { fontSize: 12, fontFamily: "Inter_600SemiBold" },
  infoBox: { flexDirection: "row", alignItems: "flex-start", gap: 10, padding: 14, borderRadius: 14, borderWidth: 1 },
  infoText: { flex: 1, fontSize: 13, fontFamily: "Inter_500Medium", lineHeight: 20 },
  scoreRow: { flexDirection: "row", alignItems: "center", borderRadius: 20, padding: 24, borderWidth: 1, marginBottom: 24, gap: 16 },
  scoreLabel: { fontSize: 20, fontFamily: "Inter_700Bold", marginBottom: 6, letterSpacing: -0.5 },
  scoreNote: { fontSize: 14, fontFamily: "Inter_500Medium", lineHeight: 20 },
  breakdownCard: { borderRadius: 16, padding: 18, borderWidth: 1, marginBottom: 24, gap: 14 },
  breakdownRow: { gap: 6 },
  breakdownLabelRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  breakdownLabel: { flex: 1, fontSize: 13, fontFamily: "Inter_600SemiBold" },
  breakdownWeight: { fontSize: 11, fontFamily: "Inter_500Medium" },
  breakdownValue: { fontSize: 13, fontFamily: "Inter_700Bold", minWidth: 40, textAlign: "right" },
  barTrack: { height: 8, borderRadius: 4, overflow: "hidden" },
  barFill: { height: "100%", borderRadius: 4 },
  suggestionCard: { borderRadius: 16, padding: 16, borderWidth: 1, marginBottom: 12 },
  suggestionHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  suggNum: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center" },
  suggTitle: { flex: 1, fontSize: 15, fontFamily: "Inter_700Bold" },
  suggestionBody: { marginTop: 14, gap: 10 },
  suggDetailRow: { flexDirection: "row", flexWrap: "wrap", alignItems: "flex-start", gap: 4 },
  suggDetailIcon: { marginTop: 2, marginRight: 2 },
  suggDetailLabel: { fontSize: 13, fontFamily: "Inter_700Bold" },
  suggDetailText: { fontSize: 13, fontFamily: "Inter_500Medium", lineHeight: 20, flexShrink: 1 },
  exampleBox: { flexDirection: "row", alignItems: "flex-start", gap: 8, padding: 12, borderRadius: 12, marginTop: 4 },
  optimizedBox: { borderRadius: 16, padding: 20, borderWidth: 1, marginBottom: 24 },
  optimizedText: { fontSize: 14, fontFamily: "Inter_500Medium", lineHeight: 24 },
  exportCard: { borderRadius: 20, padding: 20, borderWidth: 1, marginBottom: 24 },
  exportSubtitle: { fontSize: 13, fontFamily: "Inter_500Medium", marginBottom: 16, lineHeight: 20 },
  exportRow: { flexDirection: "row", gap: 10 },
  exportBtn: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, paddingVertical: 14, borderRadius: 12 },
  exportBtnText: { color: "#fff", fontFamily: "Inter_700Bold", fontSize: 13 },
  copiedBanner: { flexDirection: "row", alignItems: "center", gap: 8, padding: 10, borderRadius: 10, marginTop: 14, borderWidth: 1 },
  copiedText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  clearBtn: { flexDirection: "row", alignItems: "center", gap: 10, justifyContent: "center", paddingVertical: 16, borderRadius: 12, borderWidth: 1, marginBottom: 24 },
  clearText: { fontFamily: "Inter_600SemiBold", fontSize: 15 },
});
